In [ ]:
import pandas as pd
import numpy as np
import ast
import re

In [4]:
# since df_results is too big, put locally in your current folder (since its not on github)
csv_path = "df_results.csv"
df_raw = pd.read_csv(csv_path)
print(df_raw.shape)
print(df_raw.columns.tolist())

# if you wanna see the shape, but loading all is too long
# df = pd.read_csv("df_results.csv", nrows=1)
# print(df.head())
# print(df.info())

/var/folders/8z/zcsmsmvn04b4vm1nxr6_4v480000gq/T/ipykernel_95681/3903895202.py:3: DtypeWarning: Columns (0: postal_code) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw = pd.read_csv(csv_path)

(227932, 224)
['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date', 'remaining_lease', 'resale_price', 'postal_code', 'latitude', 'longitude', 'mrt_nearest', 'mrt_nearby', 'bus_nearest', 'bus_nearby', 'store_nearest', 'store_nearby', 'food_nearest', 'food_nearby', 'health_nearest', 'health_nearby', 'restaurant_nearest', 'restaurant_nearby', 'hospital_nearest', 'hospital_nearby', 'lodging_nearest', 'lodging_nearby', 'finance_nearest', 'finance_nearby', 'cafe_nearest', 'cafe_nearby', 'convenience_store_nearest', 'convenience_store_nearby', 'clothing_store_nearest', 'clothing_store_nearby', 'atm_nearest', 'atm_nearby', 'shopping_mall_nearest', 'shopping_mall_nearby', 'grocery_or_supermarket_nearest', 'grocery_or_supermarket_nearby', 'home_goods_store_nearest', 'home_goods_store_nearby', 'school_nearest', 'school_nearby', 'bakery_nearest', 'bakery_nearby', 'beauty_salon_nearest', 'beauty_salon_nearby', 'transit_station_nearest', 'transit_station_nearby', 'place_of_worship_nearest', 'place_of_worship_nearby', 'pharmacy_nearest', 'pharmacy_nearby', 'meal_takeaway_nearest', 'meal_takeaway_nearby', 'furniture_store_nearest', 'furniture_store_nearby', 'tourist_attraction_nearest', 'tourist_attraction_nearby', 'secondary_school_nearest', 'secondary_school_nearby', 'supermarket_nearest', 'supermarket_nearby', 'doctor_nearest', 'doctor_nearby', 'shoe_store_nearest', 'shoe_store_nearby', 'dentist_nearest', 'dentist_nearby', 'jewelry_store_nearest', 'jewelry_store_nearby', 'church_nearest', 'church_nearby', 'bank_nearest', 'bank_nearby', 'primary_school_nearest', 'primary_school_nearby', 'electronics_store_nearest', 'electronics_store_nearby', 'gym_nearest', 'gym_nearby', 'spa_nearest', 'spa_nearby', 'car_repair_nearest', 'car_repair_nearby', 'pet_store_nearest', 'pet_store_nearby', 'bus_station_nearest', 'bus_station_nearby', 'university_nearest', 'university_nearby', 'park_nearest', 'park_nearby', 'general_contractor_nearest', 'general_contractor_nearby', 'subway_station_nearest', 'subway_station_nearby', 'real_estate_agency_nearest', 'real_estate_agency_nearby', 'florist_nearest', 'florist_nearby', 'hair_care_nearest', 'hair_care_nearby', 'department_store_nearest', 'department_store_nearby', 'hardware_store_nearest', 'hardware_store_nearby', 'car_dealer_nearest', 'car_dealer_nearby', 'veterinary_care_nearest', 'veterinary_care_nearby', 'travel_agency_nearest', 'travel_agency_nearby', 'bicycle_store_nearest', 'bicycle_store_nearby', 'book_store_nearest', 'book_store_nearby', 'laundry_nearest', 'laundry_nearby', 'plumber_nearest', 'plumber_nearby', 'meal_delivery_nearest', 'meal_delivery_nearby', 'lawyer_nearest', 'lawyer_nearby', 'parking_nearest', 'parking_nearby', 'mosque_nearest', 'mosque_nearby', 'physiotherapist_nearest', 'physiotherapist_nearby', 'art_gallery_nearest', 'art_gallery_nearby', 'insurance_agency_nearest', 'insurance_agency_nearby', 'bar_nearest', 'bar_nearby', 'museum_nearest', 'museum_nearby', 'storage_nearest', 'storage_nearby', 'movie_theater_nearest', 'movie_theater_nearby', 'moving_company_nearest', 'moving_company_nearby', 'liquor_store_nearest', 'liquor_store_nearby', 'gas_station_nearest', 'gas_station_nearby', 'electrician_nearest', 'electrician_nearby', 'car_rental_nearest', 'car_rental_nearby', 'locksmith_nearest', 'locksmith_nearby', 'car_wash_nearest', 'car_wash_nearby', 'post_office_nearest', 'post_office_nearby', 'embassy_nearest', 'embassy_nearby', 'night_club_nearest', 'night_club_nearby', 'fire_station_nearest', 'fire_station_nearby', 'amusement_park_nearest', 'amusement_park_nearby', 'library_nearest', 'library_nearby', 'hindu_temple_nearest', 'hindu_temple_nearby', 'local_government_office_nearest', 'local_government_office_nearby', 'funeral_home_nearest', 'funeral_home_nearby', 'bowling_alley_nearest', 'bowling_alley_nearby', 'cemetery_nearest', 'cemetery_nearby', 'aquarium_nearest', 'aquarium_nearby', 'roofing_contractor_nearest', 'roofing_contractor_nearby', 'stadium_nearest', 'stadium_nearby', 'painter_nearest', 'painter_nearby', 'courthouse_nearest', 'courthouse_nearby', 'drugstore_nearest', 'drugstore_nearby', 'campground_nearest', 'campground_nearby', 'accounting_nearest', 'accounting_nearby', 'airport_nearest', 'airport_nearby', 'zoo_nearest', 'zoo_nearby', 'casino_nearest', 'casino_nearby', 'synagogue_nearest', 'synagogue_nearby', 'premise_nearest', 'premise_nearby', 'taxi_stand_nearest', 'taxi_stand_nearby', 'police_nearest', 'police_nearby', 'light_rail_station_nearest', 'light_rail_station_nearby', 'city_hall_nearest', 'city_hall_nearby', 'train_station_nearest', 'train_station_nearby', 'natural_feature_nearest', 'natural_feature_nearby', 'subpremise_nearest', 'subpremise_nearby']

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

df_raw.head()

     month        town flat_type block        street_name storey_range  \
0  2017-01  ANG MO KIO    2 ROOM   406  ANG MO KIO AVE 10     10 TO 12
1  2017-01  ANG MO KIO    3 ROOM   108   ANG MO KIO AVE 4     01 TO 03
2  2017-01  ANG MO KIO    3 ROOM   602   ANG MO KIO AVE 5     01 TO 03
3  2017-01  ANG MO KIO    3 ROOM   465  ANG MO KIO AVE 10     04 TO 06
4  2017-01  ANG MO KIO    3 ROOM   601   ANG MO KIO AVE 5     01 TO 03

   floor_area_sqm      flat_model  lease_commence_date     remaining_lease  \
0            44.0        Improved                 1979  61 years 04 months
1            67.0  New Generation                 1978  60 years 07 months
2            67.0  New Generation                 1980  62 years 05 months
3            68.0  New Generation                 1980   62 years 01 month
4            67.0  New Generation                 1980  62 years 05 months

   resale_price postal_code  latitude   longitude  \
0      232000.0      560406  1.362005  103.853880
1      250000.0      560108  1.370966  103.838202
2      262000.0      560602  1.380709  103.835368
3      265000.0      560465  1.366201  103.857201
4      265000.0      560601  1.381041  103.835132

                                                                                               mrt_nearest  \
0     {'name': 'ANG MO KIO MRT STATION', 'stop_id': 'NS16', 'line': 'NS', 'distance_m': 926.8978925114401}
1    {'name': 'ANG MO KIO MRT STATION', 'stop_id': 'NS16', 'line': 'NS', 'distance_m': 1316.4295661097703}
2   {'name': 'YIO CHU KANG MRT STATION', 'stop_id': 'NS15', 'line': 'NS', 'distance_m': 1071.182879336597}
3     {'name': 'ANG MO KIO MRT STATION', 'stop_id': 'NS16', 'line': 'NS', 'distance_m': 880.4238635885278}
4  {'name': 'YIO CHU KANG MRT STATION', 'stop_id': 'NS15', 'line': 'NS', 'distance_m': 1094.0129912893726}

                                                                                                  mrt_nearby  \
0     [{'name': 'ANG MO KIO MRT STATION', 'stop_id': 'NS16', 'line': 'NS', 'distance_m': 926.8978925114401}]
1    [{'name': 'ANG MO KIO MRT STATION', 'stop_id': 'NS16', 'line': 'NS', 'distance_m': 1316.4295661097703}]
2   [{'name': 'YIO CHU KANG MRT STATION', 'stop_id': 'NS15', 'line': 'NS', 'distance_m': 1071.182879336597}]
3     [{'name': 'ANG MO KIO MRT STATION', 'stop_id': 'NS16', 'line': 'NS', 'distance_m': 880.4238635885278}]
4  [{'name': 'YIO CHU KANG MRT STATION', 'stop_id': 'NS15', 'line': 'NS', 'distance_m': 1094.0129912893726}]

                                                                                  bus_nearest  \
0  {'busstop_code': 54319, 'name': 'Opp Christ The King Ch', 'distance_m': 91.92439852739197}
1   {'busstop_code': 54189, 'name': 'Mayflower Stn Exit 5', 'distance_m': 166.31237251570192}
2                 {'busstop_code': 55129, 'name': 'Blk 604', 'distance_m': 129.3446496913248}
3                 {'busstop_code': 54389, 'name': 'Blk 465', 'distance_m': 69.45283823456104}
4  {'busstop_code': 55011, 'name': 'Bef Lentor Stn Exit 5', 'distance_m': 149.89790777276488}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   bus_nearby  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [{'busstop_code': 54319, 'name': 'Opp Christ The King Ch', 'distance_m': 91.92439852739197}, {'busstop_code': 54311, 'name': 'Blk 332', 'distance_m': 158.22446822803067}, {'busstop_code': 54371, 'name': 'Blk 409 Mkt/FC', 'distance_m': 204.7920471347483}, {'busstop_code': 54379, 'name': 'Blk 475', 'distance_m': 250.0971847315535}, {'busstop_code': 54321, 'name': 'Blk 354', 'distance_m': 276.33277241102934}, {'busstop_code': 54329, 'name': 'Blk 420', 'distance_m': 317.9294434784599}, {'busstop_code': 54601, 'name': 'Townsville Pr Sch', 'distance_m': 319.85355741523784}, {'busstop_code': 54099, 'name': 'Opp Blk 333', 'distance_m': 327.63789792800907}, {'busstop_code': 54091, 'name': 'Blk 331', 'distance_m': 330.126350033029}, {'busstop_code': 54609, 'name': 'Opp Townsville Pr Sch', 'distance_m': 333.5779246570542}, {'busstop_code': 54369, 'name': 'Opp Blk 4025', 'distance_m': 425.23535862431885}, {'busstop_code': 54381, 'name': 'Blk 443', 'distance_m': 482.52726996809133}, {'busstop_code': 54531, 'name': 'Opp Bishan Pk', 'distance_m': 491.1349078218759}, {'busstop_code': 54539, 'name': 'Bishan Pk', 'distance_m': 494.8275472091169}, {'busstop_code': 54101, 'name': 'Aft Ang Mo Kio Ave 10', 'distance_m': 527.9152263037187}, {'busstop_code': 54109, 'name': 'Bef Ang Mo Kio Ave 10', 'distance_m': 549.7684657111062}, {'busstop_code': 54389, 'name': 'Blk 465', 'distance_m': 574.0708224644171}, {'busstop_code': 54089, 'name': 'Opp Ang Mo Kio Swim Cplx', 'distance_m': 608.5753093709689}, {'busstop_code': 66201, 'name': 'Opp Brockhampton Dr', 'distance_m': 643.1861612025791}, {'busstop_code': 66191, 'name': 'Aft Corfe Pl', 'distance_m': 679.2385924811198}, {'busstop_code': 54331, 'name': 'Blk 346', 'distance_m': 684.5281023688333}, {'busstop_code': 54081, 'name': 'Teck Ghee Ct', 'distance_m': 691.2722928785598}, {'busstop_code': 54339, 'name': 'Blk 422', 'distance_m': 745.8595545715331}, {'busstop_code': 53241, 'name': 'Opp Blk 217', 'distance_m': 782.9936469175595}, {'busstop_code': 54289, 'name': 'Blk 452', 'distance_m': 828.2389206288768}, {'busstop_code': 66211, 'name': 'Opp Bloxhome Dr', 'distance_m': 829.4478589524042}, {'busstop_code': 54279, 'name': 'Blk 427', 'distance_m': 854.6975150643394}, {'busstop_code': 54269, 'name': 'Opp Ang Mo Kio Stn', 'distance_m': 857.9915916288935}, {'busstop_code': 54281, 'name': 'Blk 570', 'distance_m': 866.8806791908443}, {'busstop_code': 54271, 'name': 'Blk 586', 'distance_m': 885.6551071240415}, {'busstop_code': 53439, 'name': 'Blk 228', 'distance_m': 886.7962949294034}, {'busstop_code': 54261, 'name': 'Aft Ang Mo Kio Stn Exit A', 'distance_m': 899.832811777639}, {'busstop_code': 53249, 'name': 'Blk 210', 'distance_m': 906.7540079831587}, {'busstop_code': 54299, 'name': 'Opp Blk 565', 'distance_m': 912.4082815846599}, {'busstop_code': 54079, 'name': 'Opp Blk 315', 'distance_m': 916.1364324289838}, {'busstop_code': 66181, 'name': 'Aft Chartwell Rd', 'distance_m': 956.296438152533}, {'busstop_code': 54291, 'name': 'Blk 564', 'distance_m': 972.0043065372703}, {'busstop_code': 66291, 'name': 'Aft Medway Dr', 'distance_m': 995.3775184636951}]
1  [{'busstop_code': 54189, 'name': 'Mayflower Stn Exit 5', 'distance_m': 166.31237251570192}, {'busstop_code': 54221, 'name': 'Opp Ang Mo Kio Pr Sch', 'distance_m': 191.16906195824924}, {'busstop_code': 54181, 'name': 'Mayflower Stn Exit 6', 'distance_m': 191.46835209707103}, {'busstop_code': 54229, 'name': 'Ang Mo Kio Pr Sch', 'distance_m': 244.75873126684462}, {'busstop_code': 54219, 'name': 'Opp Mayflower Sec Sch', 'distance_m': 286.54550590084136}, {'busstop_code': 54211, 'name': 'Mayflower Sec Sch', 'distance_m': 333.136473213354}, {'busstop_code': 54161, 'name': 'Opp Blk 255', 'distance_m': 375.11023783306166}, {'busstop_code': 54199, 'name': 'Bef Mayflower Stn Exit 3', 'distance_m': 375.322982075016}, {'busstop_code': 54169, 'name': 'Blk 255', 'distance_m': 381.9197347175155}, {'busstop_code': 54191, 'name': 'Mayflower Stn Exit 2', 'distance_m': 396.20006183633893}, {'busstop_code': 54231, 'name': 'Blk 129', 'distance_m': 440.0931243801397}, {'busstop_code': 54621, 'name': 'Blk 223', 'distance_m': 559.8805744546918}, {'busstop_code': 56241, 'name': "St. Nicholas Girls'", 'distance_m': 566.6917119695155}, {'busstop_code': 54201, 'name': 'Opp Blk 155', 'distance_m': 568.8217388384036}, {'busstop_code': 54629, 'name': 'Opp Blk 223', 'distance_m': 598.3922998625576}, {'busstop_code': 54239, 'name': 'Blk 209', 'distance_m': 602.4105020269265}, {'busstop_code': 54061, 'name': 'Blk 244', 'distance_m': 617.4634095425532}, {'busstop_code': 56249, 'name': "Opp St. Nicholas Girls'", 'distance_m': 618.0790310178562}, {'busstop_code': 54209, 'name': 'Bet Blks 152/155', 'distance_m': 619.759310412055}, {'busstop_code': 54069, 'name': 'Opp Blk 244', 'distance_m': 644.1181963442323}, {'busstop_code': 56289, 'name': 'Bef Shangri-La Wk', 'distance_m': 658.2154961226981}, {'busstop_code': 55111, 'name': 'Blk 180', 'distance_m': 667.6691639743565}, {'busstop_code': 55119, 'name': 'Blk 617', 'distance_m': 703.7423054701027}, {'busstop_code': 54611, 'name': 'Blk 220', 'distance_m': 724.8099739483666}, {'busstop_code': 56251, 'name': 'Opp Horizon Gdns', 'distance_m': 733.8512943833548}, {'busstop_code': 54459, 'name': 'Blk 151', 'distance_m': 742.5481204734638}, {'busstop_code': 54619, 'name': 'Opp Blk 220', 'distance_m': 745.2066307255969}, {'busstop_code': 54451, 'name': 'Blk 643', 'distance_m': 746.1383481999419}, {'busstop_code': 56259, 'name': 'Horizon Gdns', 'distance_m': 752.8991934559797}, {'busstop_code': 56269, 'name': 'Bef Ang Mo Kio Ave 2', 'distance_m': 762.3219076372415}, {'busstop_code': 56261, 'name': 'Aft Ang Mo Kio Ave 2', 'distance_m': 798.7123272862126}, {'busstop_code': 54031, 'name': 'Opp Al-Muttaqin Mque', 'distance_m': 799.6221292512441}, {'busstop_code': 54041, 'name': 'Opp Courts Ang Mo Kio', 'distance_m': 817.9854751424117}, {'busstop_code': 54049, 'name': 'Courts Ang Mo Kio', 'distance_m': 825.5438574697595}, {'busstop_code': 54011, 'name': 'Blk 207', 'distance_m': 825.8380714301584}, {'busstop_code': 54039, 'name': 'Bef Al-Muttaqin Mque', 'distance_m': 826.4666751832699}, {'busstop_code': 54019, 'name': 'Blk 307A', 'distance_m': 851.2190682519331}, {'busstop_code': 53339, 'name': 'Opp Bright Hill Tp', 'distance_m': 885.5139104359345}, {'busstop_code': 53331, 'name': 'Bef Bright Hill Tp', 'distance_m': 902.3636916991693}, {'busstop_code': 54469, 'name': 'Opp Blk 649', 'distance_m': 909.483458422994}, {'busstop_code': 54241, 'name': 'Blk 700B', 'distance_m': 909.9465269956409}, {'busstop_code': 55139, 'name': 'Blk 641', 'distance_m': 910.7589075919639}, {'busstop_code': 54461, 'name': 'Blk 649', 'distance_m': 926.4957099069766}, {'busstop_code': 53349, 'name': 'Bright Hill Stn Exit 1', 'distance_m': 941.2163519972205}, {'busstop_code': 53341, 'name': 'Bright Hill Stn Exit 2', 'distance_m': 950.3566368101543}, {'busstop_code': 54059, 'name': 'Bef Ang Mo Kio Lib', 'distance_m': 958.1114861161043}, {'busstop_code': 54248, 'name': 'Blk 324', 'distance_m': 966.479858373597}, {'busstop_code': 54051, 'name': 'Bef Ang Mo Kio Ave 5', 'distance_m': 975.5141382187929}, {'busstop_code': 55121, 'name': 'Opp Blk 604', 'distance_m': 998.7547921505223}]
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [{'busstop_code': 55129, 'name': 'Blk 604', 'distance_m': 129.3446496913248}, {'busstop_code': 55121, 'name': 'Opp Blk 604', 'distance_m': 143.30314811724963}, {'busstop_code': 55011, 'name': 'Bef Lentor Stn Exit 5', 'distance_m': 176.69198877856587}, {'busstop_code': 55019, 'name': 'Aft Lentor Stn Exit 4', 'distance_m': 183.3868395334509}, {'busstop_code': 56209, 'name': 'Bef Thomson Hills Dr', 'distance_m': 332.45953145844754}, {'busstop_code': 56201, 'name': 'Aft Munshi Abdullah Ave', 'distance_m': 347.1334394521654}, {'busstop_code': 55141, 'name': 'Opp Blk 622', 'distance_m': 415.73430808096504}, {'busstop_code': 56259, 'name': 'Horizon Gdns', 'distance_m': 433.6894548017739}, {'busstop_code': 55149, 'name': 'Blk 622', 'distance_m': 441.8369314874124}, {'busstop_code': 55119, 'name': 'Blk 617', 'distance_m': 469.94273303429924}, {'busstop_code': 55349, 'name': 'Lentor Stn Exit 5', 'distance_m': 470.87213444188376}, {'busstop_code': 55131, 'name': 'Blk 612', 'distance_m': 486.2386754922279}, {'busstop_code': 56251, 'name': 'Opp Horizon Gdns', 'distance_m': 493.3565351949311}, {'busstop_code': 55111, 'name': 'Blk 180', 'distance_m': 495.6589281446991}, {'busstop_code': 55341, 'name': 'Lentor Stn Exit 3', 'distance_m': 496.41348271562185}, {'busstop_code': 55139, 'name': 'Blk 641', 'distance_m': 558.9471473901707}, {'busstop_code': 56199, 'name': 'Aft Thomson Hills Dr', 'distance_m': 625.069887458506}, {'busstop_code': 55151, 'name': 'Ang Mo Kio Community Hosp', 'distance_m': 627.3359305456157}, {'busstop_code': 55169, 'name': 'Opp Yio Chu Kang CC', 'distance_m': 629.0436986230055}, {'busstop_code': 55159, 'name': 'Opp Ang Mo Kio Cmty Hosp', 'distance_m': 657.0877954367943}, {'busstop_code': 54209, 'name': 'Bet Blks 152/155', 'distance_m': 667.006911307149}, {'busstop_code': 55021, 'name': 'Opp Seasons Pk', 'distance_m': 669.0087794033087}, {'busstop_code': 54201, 'name': 'Opp Blk 155', 'distance_m': 682.6392278869571}, {'busstop_code': 56191, 'name': "Teachers' Housing Est", 'distance_m': 692.3045118556302}, {'busstop_code': 55029, 'name': 'Seasons Pk', 'distance_m': 693.408471514816}, {'busstop_code': 54451, 'name': 'Blk 643', 'distance_m': 697.8390504150774}, {'busstop_code': 55331, 'name': 'Aft Lentor Gr', 'distance_m': 718.4797244809157}, {'busstop_code': 55339, 'name': 'Aft Florissa Pk', 'distance_m': 734.8554468698073}, {'busstop_code': 54191, 'name': 'Mayflower Stn Exit 2', 'distance_m': 735.2140017979654}, {'busstop_code': 54199, 'name': 'Bef Mayflower Stn Exit 3', 'distance_m': 757.2774160875789}, {'busstop_code': 54459, 'name': 'Blk 151', 'distance_m': 772.4289298172864}, {'busstop_code': 55199, 'name': 'Blk 645', 'distance_m': 821.5474084890521}, {'busstop_code': 56049, 'name': 'Meadows @ Peirce', 'distance_m': 865.0019264471771}, {'busstop_code': 56041, 'name': 'Opp Meadows @ Peirce', 'distance_m': 882.7698459671466}, {'busstop_code': 56039, 'name': 'Aft Yio Chu Kang Rd', 'distance_m': 883.9355620662811}, {'busstop_code': 55371, 'name': 'Aft Lentor St', 'distance_m': 885.5593906523109}, {'busstop_code': 56031, 'name': 'Bef Yio Chu Kang Rd', 'distance_m': 896.9709722809893}, {'busstop_code': 56249, 'name': "Opp St. Nicholas Girls'", 'distance_m': 900.769361449292}, {'busstop_code': 55181, 'name': 'Opp Yio Chu Kang Stn', 'distance_m': 950.9694418025698}, {'busstop_code': 54461, 'name': 'Blk 649', 'distance_m': 962.2552181266514}, {'busstop_code': 54469, 'name': 'Opp Blk 649', 'distance_m': 984.161311851601}, {'busstop_code': 56241, 'name': "St. Nicholas Girls'", 'distance_m': 998.5984669581836}]

## Data Processing

In [ ]:
# trimmed down the data, its too many columns
# TODO: add distance / time to parent's home & office
base_cols = [
    "month",
    "flat_type",
    "block",
    "street_name",
    "storey_range",
    "floor_area_sqm",
    "flat_model",
    "remaining_lease",
    "resale_price",
    "latitude", # replaces postal code
    "longitude",
]

# TODO: we can use poi_nearby (density might be a better indicator)
poi_nearest_cols = [
    "mrt_nearest",
    "bus_nearest",
    "shopping_mall_nearest",
    "grocery_or_supermarket_nearest",
    #"supermarket_nearest", 
    "park_nearest",
    "hospital_nearest", # TODO: can drop
    "doctor_nearest",
    "pharmacy_nearest", 
    "cafe_nearest",
    "restaurant_nearest",
    "gym_nearest",
]

def extract_distance(cell):
    if pd.isna(cell):
        return np.nan
    
    if isinstance(cell, (int, float)):
        return float(cell)
    
    try:
        obj = ast.literal_eval(cell)
        if isinstance(obj, dict):
            return obj.get("distance_m", np.nan)
    except Exception:
        pass
    
    return np.nan

In [13]:
df_flats = df_raw[base_cols + poi_nearest_cols].copy()

for col in poi_nearest_cols:
    new_col = col.replace("_nearest", "_distance_m")
    df_flats[new_col] = df_flats[col].apply(extract_distance)

df_flats = df_flats.drop(columns=poi_nearest_cols)

print(df_flats.shape)
df_flats.head()

(227932, 22)

,month,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,remaining_lease,resale_price,latitude,longitude,mrt_distance_m,bus_distance_m,shopping_mall_distance_m,grocery_or_supermarket_distance_m,park_distance_m,hospital_distance_m,doctor_distance_m,pharmacy_distance_m,cafe_distance_m,restaurant_distance_m,gym_distance_m
0,2017-01,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,61 years 04 months,232000.0,1.362005,103.853880,926.897893,91.924399,1032.440827,298.943356,702.372551,759.478958,759.478958,719.191844,942.041113,675.805030,685.487900
1,2017-01,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,60 years 07 months,250000.0,1.370966,103.838202,1316.429566,166.312373,873.663121,374.856579,445.644348,380.940482,762.518468,1004.302877,1054.606053,259.598745,509.849980
2,2017-01,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,62 years 05 months,262000.0,1.380709,103.835368,1071.182879,129.344650,1531.464976,874.666963,738.579066,602.911934,1704.455313,1734.705553,1711.519153,853.948798,1629.408340
3,2017-01,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,62 years 01 month,265000.0,1.366201,103.857201,880.423864,69.452838,875.833046,574.970520,922.732931,362.911575,881.505494,262.133206,893.065336,176.628039,764.432883
4,2017-01,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,62 years 05 months,265000.0,1.381041,103.835132,1094.012991,149.897908,1575.311125,919.965695,783.742843,606.001012,1749.806066,1778.749292,1754.576301,897.963781,1673.219891

In [14]:
def parse_remaining_lease_to_years(x):
    if pd.isna(x):
        return np.nan
    
    text = str(x).lower()
    years = 0
    months = 0
    
    y_match = re.search(r"(\d+)\s*year", text)
    m_match = re.search(r"(\d+)\s*month", text)
    
    if y_match:
        years = int(y_match.group(1))
    if m_match:
        months = int(m_match.group(1))
    
    return years + months / 12

df_flats["remaining_lease_years"] = df_flats["remaining_lease"].apply(parse_remaining_lease_to_years)

In [15]:
def parse_storey_range_mid(x):
    if pd.isna(x):
        return np.nan
    try:
        parts = str(x).split(" TO ")
        low = int(parts[0])
        high = int(parts[1])
        return (low + high) / 2
    except Exception:
        return np.nan

df_flats["storey_mid"] = df_flats["storey_range"].apply(parse_storey_range_mid)

In [16]:
df_flats["flat_id"] = (
    df_flats["block"].astype(str) + "_" +
    df_flats["street_name"].astype(str) + "_" +
    df_flats["flat_type"].astype(str) + "_" +
    df_flats["month"].astype(str)
)

In [17]:
flat_feature_cols = [
    "flat_id",
    "flat_type",
    "flat_model",
    "floor_area_sqm",
    "resale_price",
    "latitude",
    "longitude",
    "remaining_lease_years",
    "storey_mid",

    # transport
    "mrt_distance_m",
    "bus_distance_m",

    # convenience
    "shopping_mall_distance_m",
    "grocery_or_supermarket_distance_m",

    # lifestyle
    "park_distance_m",
    "cafe_distance_m",
    "restaurant_distance_m",
    "gym_distance_m",

    # health
    "hospital_distance_m",
    "doctor_distance_m",
    "pharmacy_distance_m",
]

df_flats_clean = df_flats[flat_feature_cols].copy()
df_flats_clean.head()

,flat_id,flat_type,flat_model,floor_area_sqm,resale_price,latitude,longitude,remaining_lease_years,storey_mid,mrt_distance_m,bus_distance_m,shopping_mall_distance_m,grocery_or_supermarket_distance_m,park_distance_m,cafe_distance_m,restaurant_distance_m,gym_distance_m,hospital_distance_m,doctor_distance_m,pharmacy_distance_m
0,406_ANG MO KIO AVE 10_2 ROOM_2017-01,2 ROOM,Improved,44.0,232000.0,1.362005,103.853880,61.333333,11.0,926.897893,91.924399,1032.440827,298.943356,702.372551,942.041113,675.805030,685.487900,759.478958,759.478958,719.191844
1,108_ANG MO KIO AVE 4_3 ROOM_2017-01,3 ROOM,New Generation,67.0,250000.0,1.370966,103.838202,60.583333,2.0,1316.429566,166.312373,873.663121,374.856579,445.644348,1054.606053,259.598745,509.849980,380.940482,762.518468,1004.302877
2,602_ANG MO KIO AVE 5_3 ROOM_2017-01,3 ROOM,New Generation,67.0,262000.0,1.380709,103.835368,62.416667,2.0,1071.182879,129.344650,1531.464976,874.666963,738.579066,1711.519153,853.948798,1629.408340,602.911934,1704.455313,1734.705553
3,465_ANG MO KIO AVE 10_3 ROOM_2017-01,3 ROOM,New Generation,68.0,265000.0,1.366201,103.857201,62.083333,5.0,880.423864,69.452838,875.833046,574.970520,922.732931,893.065336,176.628039,764.432883,362.911575,881.505494,262.133206
4,601_ANG MO KIO AVE 5_3 ROOM_2017-01,3 ROOM,New Generation,67.0,265000.0,1.381041,103.835132,62.416667,2.0,1094.012991,149.897908,1575.311125,919.965695,783.742843,1754.576301,897.963781,1673.219891,606.001012,1749.806066,1778.749292

## Represent User Preferences :

In [ ]:
user_feature_cols = [
    "user_id",
    "budget_max",
    "preferred_flat_type",
    "min_floor_area",
    "preferred_region",
    "max_mrt_distance_m",
    "max_bus_distance_m",
    "weight_budget",
    "weight_transport",
    "weight_food",
    "weight_grocery",
    "weight_health",
    "weight_park",
    "weight_gym",
    "weight_space",
    "weight_lease",
    "weight_storey",
    "weight_location",
]

# df_users = pd.DataFrame(users)
# df_users

## Generate dummy user data

In [21]:
import pandas as pd
import numpy as np

np.random.seed(42)

flat_types = ["2 ROOM", "3 ROOM", "4 ROOM"]
flat_type_probs = [0.45, 0.4, 0.15]

regions = ["North", "North-East", "Central", "East", "West"]
region_probs = [0.18, 0.20, 0.22, 0.20, 0.20]

users = []

for i in range(100):
    users.append({
        "user_id": f"U{i+1}",
        "budget_max": np.random.choice([300000, 350000, 400000, 450000, 500000, 600000]),
        "preferred_flat_type": np.random.choice(flat_types, p=flat_type_probs),
        "min_floor_area": np.random.choice([35, 40, 45, 50, 60]),
        "preferred_region": np.random.choice(regions, p=region_probs),
        "max_mrt_distance_m": np.random.choice([500, 800, 1000, 1200]),
        "max_bus_distance_m": np.random.choice([200, 300, 500]),
        "weight_budget": np.random.choice([3, 4, 5]),
        "weight_transport": np.random.choice([3, 4, 5]),
        "weight_food": np.random.choice([3, 4, 5]),
        "weight_grocery": np.random.choice([3, 4, 5]),
        "weight_health": np.random.choice([1, 2, 3]),
        "weight_park": np.random.choice([1, 2, 3, 4]),
        "weight_gym": np.random.choice([1, 2, 3, 4]),
        "weight_space": np.random.choice([2, 3, 4, 5]),
        "weight_lease": np.random.choice([1, 2, 3]),
        "weight_storey": np.random.choice([1, 2, 3]),
        "weight_location": np.random.choice([2, 3, 4, 5]),
    })

df_users = pd.DataFrame(users)
df_users.head()
df_users = pd.DataFrame(users)

In [23]:
# because we dont expect users to input their preference lat, long
# we just ask them to input preferred region and translate here
region_centers = {
    "North": (1.4360, 103.7860),
    "North-East": (1.3880, 103.8920),
    "Central": (1.3280, 103.8420),
    "East": (1.3570, 103.9400),
    "West": (1.3450, 103.7200),
}

df_users["preferred_lat"] = df_users["preferred_region"].map(lambda r: region_centers[r][0])
df_users["preferred_lon"] = df_users["preferred_region"].map(lambda r: region_centers[r][1])

### Represent data as (user, flat) pairs
We will pair (e.g cross joining) user with the hdbs
Each row is one candidate flat for one user, later the model learns to rank flats within each user group

In [12]:
df_pairs = df_users.merge(df_flats_clean, how="cross")
print(df_pairs.shape)
df_pairs.head()

(22793200, 35)

,user_id,budget_max,preferred_flat_type,weight_budget,weight_transport,weight_school,weight_health,weight_mall,weight_park,weight_food,...,school_distance_m,primary_school_distance_m,secondary_school_distance_m,park_distance_m,hospital_distance_m,doctor_distance_m,pharmacy_distance_m,cafe_distance_m,restaurant_distance_m,gym_distance_m
0,U0,600000,2 ROOM,3,5,5,2,3,3,3,...,285.536120,285.536120,285.536120,702.372551,759.478958,759.478958,719.191844,942.041113,675.805030,685.487900
1,U0,600000,2 ROOM,3,5,5,2,3,3,3,...,422.192741,643.781805,422.192741,445.644348,380.940482,762.518468,1004.302877,1054.606053,259.598745,509.849980
2,U0,600000,2 ROOM,3,5,5,2,3,3,3,...,499.883104,499.883104,762.334388,738.579066,602.911934,1704.455313,1734.705553,1711.519153,853.948798,1629.408340
3,U0,600000,2 ROOM,3,5,5,2,3,3,3,...,501.687201,738.880530,501.687201,922.732931,362.911575,881.505494,262.133206,893.065336,176.628039,764.432883
4,U0,600000,2 ROOM,3,5,5,2,3,3,3,...,539.677677,539.677677,768.747833,783.742843,606.001012,1749.806066,1778.749292,1754.576301,897.963781,1673.219891

In [13]:
def safe_distance_score(dist_m, cap=3000):
    if pd.isna(dist_m):
        return 0.0
    dist_m = min(dist_m, cap)
    return 1 - (dist_m / cap)

df_pairs["budget_fit_score"] = np.where(
    df_pairs["resale_price"] <= df_pairs["budget_max"],
    1 - ((df_pairs["budget_max"] - df_pairs["resale_price"]) / df_pairs["budget_max"]) * 0.2,
    np.maximum(0, 1 - ((df_pairs["resale_price"] - df_pairs["budget_max"]) / df_pairs["budget_max"]))
)

df_pairs["flat_type_match"] = (
    df_pairs["flat_type"].astype(str).str.upper() ==
    df_pairs["preferred_flat_type"].astype(str).str.upper()
).astype(int)

df_pairs["area_fit_score"] = np.where(
    df_pairs["floor_area_sqm"] >= df_pairs["min_floor_area"],
    1.0,
    np.maximum(0, df_pairs["floor_area_sqm"] / df_pairs["min_floor_area"])
)

df_pairs["transport_score"] = (
    df_pairs["mrt_distance_m"].apply(safe_distance_score) * 0.7 +
    df_pairs["bus_distance_m"].apply(safe_distance_score) * 0.3
)

df_pairs["school_score"] = (
    df_pairs["primary_school_distance_m"].apply(safe_distance_score) * 0.5 +
    df_pairs["secondary_school_distance_m"].apply(safe_distance_score) * 0.5
)

df_pairs["health_score"] = (
    df_pairs["hospital_distance_m"].apply(safe_distance_score) * 0.4 +
    df_pairs["doctor_distance_m"].apply(safe_distance_score) * 0.3 +
    df_pairs["pharmacy_distance_m"].apply(safe_distance_score) * 0.3
)

df_pairs["mall_score"] = (
    df_pairs["shopping_mall_distance_m"].apply(safe_distance_score) * 0.5 +
    df_pairs["supermarket_distance_m"].apply(safe_distance_score) * 0.5
)

df_pairs["park_score"] = df_pairs["park_distance_m"].apply(safe_distance_score)

df_pairs["food_score"] = (
    df_pairs["restaurant_distance_m"].apply(safe_distance_score) * 0.5 +
    df_pairs["cafe_distance_m"].apply(safe_distance_score) * 0.5
)

### Synthetic Relevance Label

In [14]:
df_pairs["raw_relevance"] = (
    df_pairs["weight_budget"] * df_pairs["budget_fit_score"] +
    2.0 * df_pairs["flat_type_match"] +
    1.5 * df_pairs["area_fit_score"] +
    df_pairs["weight_transport"] * df_pairs["transport_score"] +
    df_pairs["weight_school"] * df_pairs["school_score"] +
    df_pairs["weight_health"] * df_pairs["health_score"] +
    df_pairs["weight_mall"] * df_pairs["mall_score"] +
    df_pairs["weight_park"] * df_pairs["park_score"] +
    df_pairs["weight_food"] * df_pairs["food_score"]
)

min_score = df_pairs["raw_relevance"].min()
max_score = df_pairs["raw_relevance"].max()

df_pairs["relevance_label"] = (
    4 * (df_pairs["raw_relevance"] - min_score) / (max_score - min_score + 1e-9)
).round().astype(int)

df_pairs[["user_id", "flat_id", "raw_relevance", "relevance_label"]].head()

,user_id,flat_id,raw_relevance,relevance_label
0,U0,406_ANG MO KIO AVE 10_2 ROOM_2017-01,22.086847,3
1,U0,108_ANG MO KIO AVE 4_3 ROOM_2017-01,20.077409,2
2,U0,602_ANG MO KIO AVE 5_3 ROOM_2017-01,18.339445,2
3,U0,465_ANG MO KIO AVE 10_3 ROOM_2017-01,20.194154,2
4,U0,601_ANG MO KIO AVE 5_3 ROOM_2017-01,18.115052,2

## Data Filter
If we directly feed df_pairs, it will throw error because each user is paired with all possible flats : <br>
[LightGBM] [Fatal] Number of rows 227932 exceeds upper limit of 10000 for a query

So we need to first filter for each user the possible flats

### Filter 1 :

In [15]:
MAX_CANDIDATES_PER_USER = 5000

df_pairs = (
    df_pairs.sort_values(["user_id", "raw_relevance"], ascending=[True, False])
    .groupby("user_id", group_keys=False)
    .head(MAX_CANDIDATES_PER_USER)
    .reset_index(drop=True)
)

print(df_pairs.groupby("user_id").size())
print(df_pairs.shape)

user_id
U0     5000
U1     5000
U10    5000
U11    5000
U12    5000
       ...
U95    5000
U96    5000
U97    5000
U98    5000
U99    5000
Length: 100, dtype: int64
(500000, 46)

### Filter 2 :

In [16]:
# Other possible filter (but it might not reduce as much as above, to a number)
# Before cross join or before training, remove obviously bad flats:
# way over budget, wrong flat type, too small floor area
def prefilter_user_candidates(user_row, flats_df):
    filtered = flats_df.copy()
    
    filtered = filtered[filtered["resale_price"] <= user_row["budget_max"] * 1.3]
    filtered = filtered[filtered["floor_area_sqm"] >= user_row["min_floor_area"] * 0.8]
    
    # optional: only exact flat type match
    filtered = filtered[filtered["flat_type"] == user_row["preferred_flat_type"]]
    
    return filtered

## Model 1 : LightGBM LambdaMART
### Pros : 
- Best fit for tabular ranking
- Handles numeric/categorical features well
- Fast
- Common for recommendation/ranking problems

#### Training matrix :

In [18]:
feature_cols = [
    # user preference features
    "budget_max",
    "weight_budget",
    "weight_transport",
    "weight_school",
    "weight_health",
    "weight_mall",
    "weight_park",
    "weight_food",
    "min_floor_area",

    # flat features
    "floor_area_sqm",
    "resale_price",
    "remaining_lease_years",
    "storey_mid",
    "mrt_distance_m",
    "bus_distance_m",
    "shopping_mall_distance_m",
    "supermarket_distance_m",
    "primary_school_distance_m",
    "secondary_school_distance_m",
    "park_distance_m",
    "hospital_distance_m",
    "doctor_distance_m",
    "pharmacy_distance_m",
    "restaurant_distance_m",
    "cafe_distance_m",
    "gym_distance_m",

    # interaction features
    "budget_fit_score",
    "flat_type_match",
    "area_fit_score",
    "transport_score",
    "school_score",
    "health_score",
    "mall_score",
    "park_score",
    "food_score",
]

#### Train / validation split by user
Ranking split by user groups

In [19]:
user_ids = df_pairs["user_id"].unique().tolist()

train_users = user_ids[: int(len(user_ids) * 0.8)]
val_users = user_ids[int(len(user_ids) * 0.8):]

train_df = df_pairs[df_pairs["user_id"].isin(train_users)].copy()
val_df = df_pairs[df_pairs["user_id"].isin(val_users)].copy()

X_train = train_df[feature_cols]
y_train = train_df["relevance_label"]

X_val = val_df[feature_cols]
y_val = val_df["relevance_label"]

train_group = train_df.groupby("user_id").size().tolist()
val_group = val_df.groupby("user_id").size().tolist()

print(train_df.shape, val_df.shape)
print(train_group, val_group)

(400000, 46) (100000, 46)
[5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000] [5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000]

#### Training Lambdamart

In [20]:
import lightgbm as lgb

train_data = lgb.Dataset(X_train, label=y_train, group=train_group)
val_data = lgb.Dataset(X_val, label=y_val, group=val_group, reference=train_data)

params = {
    "objective": "lambdarank",
    "metric": "ndcg",
    "ndcg_eval_at": [5, 10],
    "learning_rate": 0.05,
    "num_leaves": 31,
    "min_data_in_leaf": 20,
    "verbosity": -1,
}

model = lgb.train(
    params,
    train_data,
    valid_sets=[train_data, val_data],
    valid_names=["train", "val"],
    num_boost_round=200,
    callbacks=[
        lgb.early_stopping(20),
        lgb.log_evaluation(20),
    ],
)

Training until validation scores don't improve for 20 rounds
[20]	train's ndcg@5: 1	train's ndcg@10: 0.998373	val's ndcg@5: 0.97737	val's ndcg@10: 0.966445
Early stopping, best iteration is:
[1]	train's ndcg@5: 1	train's ndcg@10: 0.998339	val's ndcg@5: 0.987233	val's ndcg@10: 0.974858

#### Rank flats by each user

In [ ]:
df_pairs["pred_score"] = model.predict(df_pairs[feature_cols])

ranked = df_pairs.sort_values(["user_id", "pred_score"], ascending=[True, False])

ranked[[
    "user_id",
    "flat_id",
    "town",
    "flat_type",
    "resale_price",
    "floor_area_sqm",
    "mrt_distance_m",
    "pred_score",
    "relevance_label"
]].head(20)

# Get top 5 : 
top5 = (
    ranked.groupby("user_id", group_keys=False)
    .head(5)
    .reset_index(drop=True)
)

top5[[
    "user_id",
    "flat_id",
    "town",
    "flat_type",
    "resale_price",
    "floor_area_sqm",
    "mrt_distance_m",
    "pred_score"
]]

# if you wanna show everything and not having the ... shown : 
# print(top5.to_string())

    user_id  budget_max preferred_flat_type  weight_budget  weight_transport  weight_school  weight_health  weight_mall  weight_park  weight_food  min_floor_area                                 flat_id             town flat_type  floor_area_sqm  resale_price  latitude   longitude  remaining_lease_years  storey_mid  mrt_distance_m  bus_distance_m  shopping_mall_distance_m  grocery_or_supermarket_distance_m  supermarket_distance_m  school_distance_m  primary_school_distance_m  secondary_school_distance_m  park_distance_m  hospital_distance_m  doctor_distance_m  pharmacy_distance_m  cafe_distance_m  restaurant_distance_m  gym_distance_m  budget_fit_score  flat_type_match  area_fit_score  transport_score  school_score  health_score  mall_score  park_score  food_score  raw_relevance  relevance_label  pred_score
0        U0      600000              2 ROOM              3                 5              5              2            3            3            3              90      440A_CLEMENTI AVE 3_2 ROOM_2023-05         CLEMENTI    2 ROOM            47.0      492000.0  1.315999  103.764198              94.250000         8.0      168.726476      104.406407                146.701898                          98.826001               98.826001         127.828150                 127.828150                   221.922824       493.031109           225.542906         311.513516           111.822373        83.467652              70.629655      757.984904          0.964000                1        0.522222         0.950190      0.941708      0.927594    0.959079    0.835656    0.974317      25.297168                3    0.097261
1        U0      600000              2 ROOM              3                 5              5              2            3            3            3              90            32_NEW MKT RD_2 ROOM_2023-06     CENTRAL AREA    2 ROOM            63.0      430000.0  1.284859  103.842579              58.833333         5.0      109.391318       99.362905                 73.344284                          93.276694               93.276694         636.999097                 959.529512                   636.999097       330.439296           125.594931         183.548408           140.580336       152.587217              41.408860      185.388451          0.943333                1        0.700000         0.964539      0.733912      0.950841    0.972230    0.889854    0.967667      24.763189                3    0.097261
2        U0      600000              2 ROOM              3                 5              5              2            3            3            3              90            32_NEW MKT RD_2 ROOM_2022-08     CENTRAL AREA    2 ROOM            63.0      420000.0  1.284859  103.842579              59.750000         8.0      109.391318       99.362905                 73.344284                          93.276694               93.276694         636.999097                 959.529512                   636.999097       330.439296           125.594931         183.548408           140.580336       152.587217              41.408860      185.388451          0.940000                1        0.700000         0.964539      0.733912      0.950841    0.972230    0.889854    0.967667      24.753189                3    0.097261
3        U0      600000              2 ROOM              3                 5              5              2            3            3            3              90            32_NEW MKT RD_2 ROOM_2025-09     CENTRAL AREA    2 ROOM            52.0      395000.0  1.284859  103.842579              56.500000         8.0      109.391318       99.362905                 73.344284                          93.276694               93.276694         636.999097                 959.529512                   636.999097       330.439296           125.594931         183.548408           140.580336       152.587217              41.408860      185.388451          0.931667                1        0.577778         0.964539      0.733912      0.950841    0.972230    0.889854    0.967667      24.544856                3    0.097261
4        U0      600000              2 ROOM              3                 5              5              2            3            3            3              90            32_NEW MKT RD_2 ROOM_2025-06     CENTRAL AREA    2 ROOM            52.0      393333.0  1.284859  103.842579              56.750000         8.0      109.391318       99.362905                 73.344284                          93.276694               93.276694         636.999097                 959.529512                   636.999097       330.439296           125.594931         183.548408           140.580336       152.587217              41.408860      185.388451          0.931111                1        0.577778         0.964539      0.733912      0.950841    0.972230    0.889854    0.967667      24.543189                3    0.097261
5        U1      600000              5 ROOM              3                 5              2              4            2            4            5              40   340_CHOA CHU KANG LOOP_5 ROOM_2022-01    CHOA CHU KANG    5 ROOM           123.0      580000.0  1.384098  103.745499              70.416667         5.0      133.331191       79.341636                130.592147                         138.360280              138.360280         358.676692                 358.676692                   675.549230       364.864265            43.328197          43.328197           165.744803        89.029784              75.653845     3133.811365          0.993333                1        1.000000         0.960955      0.827629      0.973316    0.955175    0.878379    0.972553      27.119924                3    0.097261
6        U1      600000              5 ROOM              3                 5              2              4            2            4            5              40   346_CHOA CHU KANG LOOP_5 ROOM_2021-09    CHOA CHU KANG    5 ROOM           123.0      555388.0  1.383590  103.744901              70.750000         8.0      143.871231       84.247929                169.791198                         180.025959              180.025959         354.555666                 354.555666                   703.258822       448.987431            70.003596          70.003596           201.270120        71.739299              72.075109     3136.868459          0.985129                1        1.000000         0.958005      0.823698      0.963539    0.941697    0.850338    0.976031      26.911864                3    0.097261
7        U1      600000              5 ROOM              3                 5              2              4            2            4            5              40     710_ANG MO KIO AVE 8_5 ROOM_2019-10       ANG MO KIO    5 ROOM           117.0      555000.0  1.371046  103.848187              60.000000         5.0      270.830736       57.189694                 96.338456                         130.061530              130.061530         569.092177                 683.309377                   728.004434       231.779169           138.615066          47.821636           119.066458        79.584901             201.275154      975.988541          0.985000                1        1.000000         0.931087      0.764781      0.964829    0.962267    0.922740    0.953190      26.880759                3    0.097261
8        U1      600000              5 ROOM              3                 5              2              4            2            4            5              40   346_CHOA CHU KANG LOOP_5 ROOM_2018-01    CHOA CHU KANG    5 ROOM           125.0      480000.0  1.383590  103.744901              74.416667         5.0      143.871231       84.247929                169.791198                         180.025959              180.025959         354.555666                 354.555666                   703.258822       448.987431            70.003596          70.003596           201.270120        71.739299              72.075109     3136.868459          0.960000                1        1.000000         0.958005      0.823698      0.963539    0.941697    0.850338    0.976031      26.836476                3    0.097261
9        U1      600000              5 ROOM              3                 5              2              4            2            4            5              40     710_ANG MO KIO AVE 8_5 ROOM_2022-05       ANG MO KIO    5 ROOM           117.0      620000.0  1.371046  103.848187              57.416667         5.0      270.830736       57.189694                 96.338456                         130.061530              130.061530         569.092177                 683.309377                   728.004434       231.779169           138.615066          47.821636           119.066458        79.584901             201.275154      975.988541          0.966667                1        1.000000         0.931087      0.764781      0.964829    0.962267    0.922740    0.953190      26.825759                3    0.097261
10      U10      500000              2 ROOM              2                 2              1              4            1            4            2              40            32_NEW MKT RD_2 ROOM_2023-06     CENTRAL AREA    2 ROOM            63.0      430000.0  1.284859  103.842579              58.833333         5.0      109.391318       99.362905                 73.344284                          93.276694               93.276694         636.999097                 959.529512                   636.999097       330.439296           125.594931         183.548408           140.580336       152.587217              41.408860      185.388451          0.972000                1        1.000000         0.964539      0.733912      0.950841    0.972230    0.889854    0.967667      18.377333                2    0.097261
11      U10      500000              2 ROOM              2                 2              1              4            1            4            2              40            32_NEW MKT RD_2 ROOM_2022-08     CENTRAL AREA    2 ROOM            63.0      420000.0  1.284859  103.842579              59.750000         8.0      109.391318       99.362905                 73.344284                          93.276694               93.276694         636.999097                 959.529512                   636.999097       330.439296           125.594931         183.548408           140.580336       152.587217              41.408860      185.388451          0.968000                1        1.000000         0.964539      0.733912      0.950841    0.972230    0.889854    0.967667      18.369333                2    0.097261
12      U10      500000              2 ROOM              2                 2              1              4            1            4            2              40            32_NEW MKT RD_2 ROOM_2025-09     CENTRAL AREA    2 ROOM            52.0      395000.0  1.284859  103.842579              56.500000         8.0      109.391318       99.362905                 73.344284                          93.276694               93.276694         636.999097                 959.529512                   636.999097       330.439296           125.594931         183.548408           140.580336       152.587217              41.408860      185.388451          0.958000                1        1.000000         0.964539      0.733912      0.950841    0.972230    0.889854    0.967667      18.349333                2    0.097261
13      U10      500000              2 ROOM              2                 2              1              4            1            4            2              40            32_NEW MKT RD_2 ROOM_2025-06     CENTRAL AREA    2 ROOM            52.0      393333.0  1.284859  103.842579              56.750000         8.0      109.391318       99.362905                 73.344284                          93.276694               93.276694         636.999097                 959.529512                   636.999097       330.439296           125.594931         183.548408           140.580336       152.587217              41.408860      185.388451          0.957333                1        1.000000         0.964539      0.733912      0.950841    0.972230    0.889854    0.967667      18.348000                2    0.097261
14      U10      500000              2 ROOM              2                 2              1              4            1            4            2              40            32_NEW MKT RD_2 ROOM_2025-02     CENTRAL AREA    2 ROOM            52.0      391888.0  1.284859  103.842579              57.166667         8.0      109.391318       99.362905                 73.344284                          93.276694               93.276694         636.999097                 959.529512                   636.999097       330.439296           125.594931         183.548408           140.580336       152.587217              41.408860      185.388451          0.956755                1        1.000000         0.964539      0.733912      0.950841    0.972230    0.889854    0.967667      18.346844                2    0.097261
15      U11      700000              4 ROOM              4                 3              3              1            3            5            3              40  627_CHOA CHU KANG ST 62_4 ROOM_2025-06    CHOA CHU KANG    4 ROOM           101.0      590000.0  1.397930  103.746086              71.000000         5.0      153.060122       91.101322                 83.447397                          83.058229               83.058229         175.174118                 517.611917                   175.174118       299.301173          1532.614880        1532.614880            96.497963       109.451222             103.189312     4373.619651          0.968571                1        1.000000         0.955176      0.884536      0.632740    0.972249    0.900233    0.964560      23.837752                3    0.100000
16      U11      700000              4 ROOM              4                 3              3              1            3            5            3              40  562_CHOA CHU KANG ST 52_4 ROOM_2026-01    CHOA CHU KANG    4 ROOM           108.0      588000.0  1.396299  103.746023              68.500000        11.0      206.188303       98.611291                131.643750                         128.222040              128.222040         355.901713                 359.202457                   355.901713       294.074060          1351.174767        1351.174767           111.020718       125.078939              86.391550     4216.821412          0.968000                1        1.000000         0.942028      0.880816      0.673624    0.956689    0.901975    0.964755      23.788365                3    0.100000
17      U11      700000              4 ROOM              4                 3              3              1            3            5            3              40  569_CHOA CHU KANG ST 52_4 ROOM_2025-09    CHOA CHU KANG    4 ROOM           106.0      575000.0  1.396085  103.746375              68.833333        11.0      197.804774      117.362118                130.060839                         139.845620              139.845620         318.390547                 318.390547                   318.390547       338.865685          1330.989888        1330.989888           121.739389       124.688318              77.666854     4177.251997          0.964286                1        1.000000         0.942109      0.893870      0.677262    0.955016    0.887045    0.966274      23.741435                3    0.100000
18      U11      700000              4 ROOM              4                 3              3              1            3            5            3              40  626_CHOA CHU KANG ST 62_4 ROOM_2025-12    CHOA CHU KANG    4 ROOM           100.0      600000.0  1.398321  103.745878              70.500000         5.0      190.915431       75.564920                111.697322                         131.909853              131.909853         131.068379                 566.550431                   131.068379       294.015460          1574.545241        1574.545241           145.709481       157.030295             140.624077     4422.833784          0.971429                1        1.000000         0.947897      0.883730      0.618035    0.959399    0.901995    0.950391      23.737973                3    0.100000
19      U11      700000              4 ROOM              4                 3              3              1            3            5            3              40  569_CHOA CHU KANG ST 52_4 ROOM_2024-05    CHOA CHU KANG    4 ROOM           105.0      570000.0  1.396085  103.746375              70.166667         5.0      197.804774      117.362118                130.060839                         139.845620              139.845620         318.390547                 318.390547                   318.390547       338.865685          1330.989888        1330.989888           121.739389       124.688318              77.666854     4177.251997          0.962857                1        1.000000         0.942109      0.893870      0.677262    0.955016    0.887045    0.966274      23.735721                3    0.100000
20      U12      700000              3 ROOM              3                 1              2              2            4            5            3              40          264_WATERLOO ST_3 ROOM_2025-06     CENTRAL AREA    3 ROOM            68.0      638000.0  1.299009  103.852285              60.333333         8.0      211.898677       66.154919                 33.228312                         365.962640              365.962640         149.028788                 277.327498                   277.327498        37.473694           124.409916         198.734281           342.511773       110.321521             219.586441      409.906258          0.982286                1        1.000000         0.943941      0.907558      0.929287    0.933468    0.987509    0.945015      22.570951                3    0.097261
21      U12      700000              3 ROOM              3                 1              2              2            4            5            3              40          264_WATERLOO ST_3 ROOM_2025-05     CENTRAL AREA    3 ROOM            68.0      618000.0  1.299009  103.852285              60.416667        17.0      211.898677       66.154919                 33.228312                         365.962640              365.962640         149.028788                 277.327498                   277.327498        37.473694           124.409916         198.734281           342.511773       110.321521             219.586441      409.906258          0.976571                1        1.000000         0.943941      0.907558      0.929287    0.933468    0.987509    0.945015      22.553808                3    0.097261
22      U12      700000              3 ROOM              3                 1              2              2            4            5            3              40          264_WATERLOO ST_3 ROOM_2025-11     CENTRAL AREA    3 ROOM            60.0      565000.0  1.299009  103.852285              59.916667        11.0      211.898677       66.154919                 33.228312                         365.962640              365.962640         149.028788                 277.327498                   277.327498        37.473694           124.409916         198.734281           342.511773       110.321521             219.586441      409.906258          0.961429                1        1.000000         0.943941      0.907558      0.929287    0.933468    0.987509    0.945015      22.508380                3    0.097261

## Model 2 : XGBoost Ranker
XGBoost turns out to be using lambdamart, too as its underlying algorithm. But we can try both

In [23]:
from xgboost import XGBRanker
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

target_col = "relevance_label"
group_col = "user_id"

In [24]:
# Again, split by user
user_ids = df_pairs[group_col].unique().tolist()

train_users, test_users = train_test_split(
    user_ids,
    test_size=0.33,
    random_state=42
)

train_df = df_pairs[df_pairs[group_col].isin(train_users)].copy()
test_df = df_pairs[df_pairs[group_col].isin(test_users)].copy()

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

Train shape: (335000, 47)
Test shape: (165000, 47)

In [25]:
# Sort before grouping 
train_df = train_df.sort_values([group_col, "flat_id"]).reset_index(drop=True)
test_df = test_df.sort_values([group_col, "flat_id"]).reset_index(drop=True)

X_train = train_df[feature_cols]
y_train = train_df[target_col]

X_test = test_df[feature_cols]
y_test = test_df[target_col]

train_group = train_df.groupby(group_col).size().tolist()
test_group = test_df.groupby(group_col).size().tolist()

print("Train groups:", train_group)
print("Test groups:", test_group)

Train groups: [5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000]
Test groups: [5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000]

### Training XGBoost ranker

In [26]:
xgb_ranker = XGBRanker(
    objective="rank:ndcg",
    learning_rate=0.05,
    max_depth=6,
    n_estimators=200,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb_ranker.fit(
    X_train,
    y_train,
    group=train_group,
    verbose=True
)

XGBRanker(base_score=None, booster=None, callbacks=None, colsample_bylevel=None,
          colsample_bynode=None, colsample_bytree=0.8, device=None,
          early_stopping_rounds=None, enable_categorical=False,
          eval_metric=None, feature_types=None, gamma=None, grow_policy=None,
          importance_type=None, interaction_constraints=None,
          learning_rate=0.05, max_bin=None, max_cat_threshold=None,
          max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
          max_leaves=None, min_child_weight=None, missing=nan,
          monotone_constraints=None, multi_strategy=None, n_estimators=200,
          n_jobs=None, num_parallel_tree=None, random_state=42, ...)

### Prediction + rank

In [27]:
test_df["pred_score_xgb"] = xgb_ranker.predict(X_test)

ranked_test_xgb = test_df.sort_values(
    [group_col, "pred_score_xgb"],
    ascending=[True, False]
).reset_index(drop=True)

### Top 5 each user :

In [28]:
top5_xgb = (
    ranked_test_xgb.groupby(group_col, group_keys=False)
    .head(5)
    .reset_index(drop=True)
)

top5_xgb[[
    "user_id",
    "flat_id",
    "flat_type",
    "resale_price",
    "floor_area_sqm",
    "mrt_distance_m",
    "pred_score_xgb"
]]

,user_id,flat_id,flat_type,resale_price,floor_area_sqm,mrt_distance_m,pred_score_xgb
0,U0,440A_CLEMENTI AVE 3_2 ROOM_2023-05,2 ROOM,492000.0,47.0,168.726476,4.168982
1,U0,32_NEW MKT RD_2 ROOM_2023-06,2 ROOM,430000.0,63.0,109.391318,3.100995
2,U0,32_NEW MKT RD_2 ROOM_2022-08,2 ROOM,420000.0,63.0,109.391318,3.089757
3,U0,32_NEW MKT RD_2 ROOM_2024-06,2 ROOM,388000.0,52.0,109.391318,2.310727
4,U0,32_NEW MKT RD_2 ROOM_2025-02,2 ROOM,391888.0,52.0,109.391318,2.310727
...,...,...,...,...,...,...,...
160,U96,323_ANG MO KIO AVE 3_2 ROOM_2022-09,2 ROOM,285000.0,44.0,294.003601,4.459447
161,U96,323_ANG MO KIO AVE 3_2 ROOM_2022-10,2 ROOM,280000.0,48.0,294.003601,4.459447
162,U96,323_ANG MO KIO AVE 3_2 ROOM_2023-01,2 ROOM,300000.0,49.0,294.003601,4.459447
163,U96,323_ANG MO KIO AVE 3_2 ROOM_2023-08,2 ROOM,300000.0,44.0,294.003601,4.459447
164,U96,323_ANG MO KIO AVE 3_2 ROOM_2023-12,2 ROOM,288000.0,44.0,294.003601,4.459447

### NDCG@5 Metrics

In [29]:
def dcg_at_k(relevances, k):
    relevances = np.asarray(relevances)[:k]
    if relevances.size == 0:
        return 0.0
    return np.sum((2 ** relevances - 1) / np.log2(np.arange(2, relevances.size + 2)))

def ndcg_at_k(y_true, y_score, k=5):
    order = np.argsort(y_score)[::-1]
    y_true_sorted_by_pred = np.take(y_true, order)
    dcg = dcg_at_k(y_true_sorted_by_pred, k)

    ideal_order = np.argsort(y_true)[::-1]
    y_true_sorted_ideal = np.take(y_true, ideal_order)
    idcg = dcg_at_k(y_true_sorted_ideal, k)

    if idcg == 0:
        return 0.0
    return dcg / idcg

In [30]:
ndcg_scores_xgb = []

for user_id, group in ranked_test_xgb.groupby("user_id"):
    score = ndcg_at_k(
        group["relevance_label"].values,
        group["pred_score_xgb"].values,
        k=5
    )
    ndcg_scores_xgb.append(score)

print("Mean NDCG@5:", np.mean(ndcg_scores_xgb))

Mean NDCG@5: 0.9962946101344671

### Feature importance

In [31]:
importance_df = pd.DataFrame({
    "feature": feature_cols,
    "importance": xgb_ranker.feature_importances_
}).sort_values("importance", ascending=False)

importance_df.head(15)

                        feature  importance
31                 health_score    0.222464
34                   food_score    0.135276
23        restaurant_distance_m    0.067463
27              flat_type_match    0.065089
24              cafe_distance_m    0.059755
33                   park_score    0.044962
16       supermarket_distance_m    0.041031
19              park_distance_m    0.034274
20          hospital_distance_m    0.031274
21            doctor_distance_m    0.025450
26             budget_fit_score    0.024316
15     shopping_mall_distance_m    0.019905
29              transport_score    0.018110
18  secondary_school_distance_m    0.017556
13               mrt_distance_m    0.016565

## Other checks :

In [32]:
print(df_pairs["relevance_label"].describe())
print(df_pairs["relevance_label"].value_counts())

count    500000.000000
mean          2.493360
std           0.558742
min           1.000000
25%           2.000000
50%           2.000000
75%           3.000000
max           4.000000
Name: relevance_label, dtype: float64
2    253918
3    230523
4     10572
1      4987
Name: relevance_label, dtype: int64

In [33]:
print(X_train.nunique().sort_values())

flat_type_match                   2
budget_max                        5
weight_budget                     5
weight_transport                  5
weight_school                     5
weight_health                     5
weight_mall                       5
weight_park                       5
weight_food                       5
min_floor_area                    5
storey_mid                       17
area_fit_score                  110
floor_area_sqm                  124
remaining_lease_years           679
resale_price                   2263
school_score                   4114
transport_score                4114
mall_score                     4114
cafe_distance_m                4114
gym_distance_m                 4114
health_score                   4114
restaurant_distance_m          4114
primary_school_distance_m      4114
doctor_distance_m              4114
hospital_distance_m            4114
park_distance_m                4114
secondary_school_distance_m    4114
park_score                     4114
supermarket_distance_m         4114
shopping_mall_distance_m       4114
bus_distance_m                 4114
mrt_distance_m                 4114
pharmacy_distance_m            4114
food_score                     4114
budget_fit_score               5401
dtype: int64

In [34]:
print(train_df.groupby("user_id").size())

user_id
U1     5000
U10    5000
U11    5000
U13    5000
U14    5000
       ...
U94    5000
U95    5000
U97    5000
U98    5000
U99    5000
Length: 67, dtype: int64

In [35]:
pred = xgb_ranker.predict(X_train)
print(pred[:20])
print(np.unique(pred))

[-4.1829867 -4.0911164 -4.1829867 -4.0911164 -4.1318836 -3.7957642
 -3.8384843 -3.9028563 -3.7957642 -3.9028563 -3.997077  -3.9460073
 -3.9308345 -4.0892186 -3.997077  -3.8247051 -3.9629054 -4.0932636
 -4.0932636 -4.1313744]
[-4.8393483 -4.8074417 -4.8047647 ...  4.4887342  4.4892874  4.4942327]